### ISSUE TITLE
Broken for grayscale

### ISSUE THREAD

**Issue by danawoodman** [pburtchaell/shader#2]
If I use with grayscale, say `#aaa` I get shades of purple. Not sure if this is intended behavior or not...

**Comment by pburtchaell** [comment]
Hi @danawoodman. No, this is not intended, but the library only supports hex codes that are six chars long, e.g., you need to use `#aaaaaa`.

**Comment by pburtchaell** [comment]
Update, I fixed this issue and released it to npm as `shader@1.0.0`. The new version will support the following hex codes:

- 3 chars: `fff`
- 4 chars: `#fff`
- 6 chars: `ffffff`
- 7 chars: `#ffffff`

Let me know if you have any other issues!

**Comment by danawoodman** [comment]
Thanks for the quick work @pburtchaell 🍻
